version: 2

jobs:
  build:
    working_directory: /project
    docker:
      - image: archimg/base-devel
    steps:
      - checkout
      - restore_cache:
          key: yay-cache
      - run:
          name: Setup build environment
          command: make setup
      - run:
          name: Setup tools
          command: sudo -ubuild make tools
      - run:
          name: Build packages
          command: sudo -ubuild make packages
      - run:
          name: Create repository
          command: make repository
      - save_cache:
          key: yay-cache
          paths:
            - /tmp/build
      - persist_to_workspace:
          root: /tmp/repository
          paths:
            - .
  deploy:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/repository
      - run:
          name: Commit
          command: make commit
      - run:
          name: Push to Github
          command: make push

workflows:
  version: 2
  update:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "10 10 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy:
          requires:
            - build
