version: 2

jobs:
  build:
    working_directory: /project
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Install development toolchain
          command: pacman -Syu --noconfirm --needed base-devel
      - run:
          name: Setup build environment
          command: make setup
      - restore_cache:
          key: CACHE-ARCH-REPO-V1
      - run:
          name: Build packages
          command: sudo -ubuild make packages
      - save_cache:
          key: CACHE-ARCH-REPO-V1
          paths:
            - /tmp/build
            - /tmp/ccache
      - run:
          name: Create repository
          command: make repository
      - persist_to_workspace:
          root: /tmp/repository
          paths:
            - .
  deploy:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/repository
      - run:
          name: Commit
          command: make commit
      - run:
          name: Push to Github
          command: make push

workflows:
  version: 2
  update:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "10 10 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy:
          requires:
            - build
