name: release

# Take a look at https://aur.chaotic.cx/, I am commenting some packages that are already present there

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 6 * * * # Run 11:30 PM Indian Standard Time

env:
  COUNTRY: United States # Github actions hosted in US servers
  REPO_DIR: /tmp/repo
  BUILD_DIR: /tmp/build
  PKGS_DIR: /tmp/_packages_
  CCACHE_DIR: /tmp/ccache
  GIT_REMOTE: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  GIT_BRANCH: gh-pages
  GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    strategy:
      matrix:
        package:
          - yay-bin # [!] You should not remove this. This workflow uses self-built yay to build other packages.
          #- anydesk-bin    # present in chaotic-aur
          #- ddgr-git
          #- devdocs-desktop
          #- elementary-planner-git
          #- elementary-sherlock
          #- freedownloadmanager    # present in chaotic-aur
          #- arm-linux-gnueabihf-gcc
          #- gnome-terminal-transparency
          #- google-cloud-sdk    # present in chaotic-aur
          #- heroku-cli-bin    # present in chaotic-aur
          - neovim-coc-bin
          - neovim-coc-clangd-git
          - neovim-coc-rust-analyzer-git
          - pdfrankenstein
          - polybar
          #- python-conda
          #- python-conda-package-handling
          - rust-book-git
          #- rustdesk-bin    # present in chaotic-aur
          #- teams
          #- telegram-tg-git
          - ulauncher-revived-git
          #- vlc-git    # present in chaotic-aur
          #- vscodium-bin
          #- vscodium-bin-features
          #- vscodium-bin-marketplace
          #- wine-stable
          #- wine-no-pe
          #- wine-mono
          - whatscli-git
          #- youtube-music-bin    # present in chaotic-aur
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: cache-${{ matrix.package }}
          path: |
            ${{ env.BUILD_DIR }}
            ${{ env.CCACHE_DIR }}
      - run: |
          ./tasks.sh initialize
      # Add multilib too, required for building wine
      #- run: printf "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
      - run: |
          ./tasks.sh package ${{ matrix.package }}
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.package }}
          path: ${{ env.PKGS_DIR }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ${{ env.PKGS_DIR }}
      - run: |
          ./tasks.sh repository
      - run: |
          ./tasks.sh setup_git
      - run: |
          ./tasks.sh commit
      - run: |
          ./tasks.sh push
