name: release

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 15 * * * # <- You can change this

env:
  COUNTRY: United States # [!] Do not change. This env is used to find fast mirror server. (Github Actions' workers are running in US.)
  UPSTREAM: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  GITHUB_USER: ${{ github.repository_owner }}

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: archlinux
    strategy:
      matrix:
        package: # <- You can change this
          - yay # [!] You should not remove this. This job uses self-built yay to build other packages.
          - libnss-stns
          - mongodb-bin
          - nodenv
          - openresty_luarocks
          - phantomjs-bin
          - s3ql
          - softethervpn
          - stns
          - zfs-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: cache-${{ matrix.package }}
          path: |
            /tmp/build
            /tmp/ccache
      - run: |
          ./tasks.sh mirrorlist
      - run: |
          ./tasks.sh setup
      - run: |
          ./tasks.sh package ${{ matrix.package }}
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.package }}
          path: /tmp/build
  publish:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: /tmp/build
      - run: |
          ./tasks.sh repository
      - run: |
          ./tasks.sh setup_git
      - run: |
          ./tasks.sh commit
      - run: |
          ./tasks.sh push
